# Detect generates markdown from the source code using the gradle task 'docs'.
# The task uses freemarker ftl files inside 'templates' and the files inside 'static' to create files fed to mkdocs.
# The generated markdown is placed inside 'generated' and 'mkdocs build' is run against that markdown and creates a 'site' directory.
# Neither the 'generated' folder nor the mkdocs 'site' folder should be added to source control.
# After running the 'docs' task, the 'site' folder can be uploaded to gh-pages.
site_name: Synopsys Detect
theme:
  name: 'material'
docs_dir: 'generated'