# Detect generates markdown from the source code using the gradle task 'docs'.
# The task uses freemarker ftl files inside 'templates' and the files inside 'static' to create files fed to mkdocs.
# The generated markdown is placed inside 'generated' and 'mkdocs build' is run against that markdown and creates a 'site' directory.
# Neither the 'generated' folder nor the mkdocs 'site' folder should be added to source control.
# After running the 'docs' task, the 'site' folder can be uploaded to gh-pages.
# To build, install pip and python, then execute:
#   pip install mkdocs
#   pip install mkdocs-material
# To view the docs, you must execute:
#   At project root: gradlew docs
#   At docs/site: mkdocs serve
site_name: Synopsys Detect
theme:
  name: 'material'
  features:
    - navigation.indexes
docs_dir: 'generated'
markdown_extensions:
  - toc:
      permalink: "#"
nav:
     - <b>Documentation</b>: index.md
     - Overview: 00-introduction.md
     - Getting Started:
       - 15-gettingstarted/index.md
       - Key Concepts and Terms: 15-gettingstarted/terms.md
       - How Synopsys Detect Works: 15-gettingstarted/howitworks.md
       - Synopsys Detect Basic Workflow: 15-gettingstarted/workflow.md
       - Configuring Synopsys Detect Processing: 15-gettingstarted/configuring.md
       - Users and Roles: 15-gettingstarted/usersandroles.md
       - Getting Help: 15-gettingstarted/gettinghelp.md
     - Requirements: 10-requirements.md
     - Quick Start: 20-quickstart.md
     - Running: 30-running.md
     - Configuring: 40-configuring.md
     - Quick Reference: 70-quickreference.md
     - Release notes: 90-releasenotes.md



