# Detect generates markdown from the source code using the gradle task 'docs'.
# The task uses freemarker ftl files inside 'templates' and the files inside 'static' to create files fed to mkdocs.
# The generated markdown is placed inside 'generated' and 'mkdocs build' is run against that markdown and creates a 'site' directory.
# Neither the 'generated' folder nor the mkdocs 'site' folder should be added to source control.
# After running the 'docs' task, the 'site' folder can be uploaded to gh-pages.
# To build, install pip and python, then execute:
#   pip install mkdocs
#   pip install mkdocs-material
# To view the docs, you must execute:
#   At project root: gradlew docs
#   At docs/site: mkdocs serve
site_name: Synopsys Detect
theme:
  name: 'material'
  features:
    - navigation.indexes
docs_dir: 'generated'
markdown_extensions:
  - toc:
      permalink: "#"
nav:
     - <b>Documentation</b>: index.md
     - Overview: 00-introduction.md
     - Getting Started:
       - 15-gettingstarted/index.md
       - 15-gettingstarted/terms.md
       - 15-gettingstarted/howitworks.md
       - 15-gettingstarted/workflow.md
       - 15-gettingstarted/configuring.md
       - 15-gettingstarted/usersandroles.md
       - 15-gettingstarted/gettinghelp.md
     - Requirements: 10-requirements.md
     - Quick Start: 20-quickstart.md
     - Getting and Running Detect:
       - 23-downloadingandrunning/index.md
       - 23-downloadingandrunning/codeverification.md
       - 23-downloadingandrunning/includingexcluding.md
       - 23-downloadingandrunning/downloadlocations.md
       - 23-downloadingandrunning/airgap.md
       - 23-downloadingandrunning/rapidscan.md
       - advanced/status-file.md
       - 23-downloadingandrunning/proxies.md
       - 23-downloadingandrunning/concurrent.md
     - Naming:
       - 27-naming/index.md
       - 27-naming/aggregation.md
     - Configuring: 40-configuring.md
     - Results:
       - 50-results/index.md
       - 50-results/reports.md
     - Troubleshooting:
       - 60-troubleshooting/index.md
       - 60-troubleshooting/diagnosticmode.md
       - advanced/troubleshooting/exit-codes.md
       - 60-troubleshooting/solutions.md
       - 60-troubleshooting/usage-metrics.md
     - Shell Script Reference:
       - 70-scripts/index.md
       - 70-scripts/script-escaping-special-characters.md
     - Components:
       - components/index.md
       - components/tools.md
       - components/detectors.md
       - components/inspectors.md
     - Properties:
       - properties/index.md
       - properties/all-properties.md
     - Package Manager Information
     - Release notes: 90-releasenotes.md
     - Find a home for
     - Running: 30-running.md
     - Quick Reference: 70-quickreference.md



